### PR TITLE
make cleanCache work under stack-roots directory structure

### PR DESCRIPTION
**Pull request by jonschoning**
cleanCache was not removing files in ~/.stack/indices/Hackage. 
cleanCache now detects when stack is being used and traverses an additional directory level deeper in order to find tag files to delete

### CODE REVIEW

**Comment by bitemyapp** [comment]
Seems good but reminds me I'd like to get a build+test suite via TravisCI going for this.

**Comment by jonschoning** [comment]
i realize this also alters the behavior of cleanCache; if it's too much of a breaking change no worries, can close.   

some context: Just got caught when switching between emacs and vim formats, and spent some time hunting why it seemed like it was generating an invalid emacs TAGS file (problem went away after manually removing those existing tag files.)

**Comment by bitemyapp** [comment]
I think it's a good change and unless @aloiscochard says otherwise, I'll merge it. I'm just griping that I hadn't gotten a basic test in place.

**Comment by bitemyapp** [comment]
@jonschoning all done here I think. Thanks!

**Pull request merged**
