### PR TITLE
Issue #13

### PR DESCRIPTION
**Pull request by talw**
And some linting,and a dep bump for Cabal.
Perhaps I should have splitted this?

### CODE REVIEW

**Comment by aloiscochard** [comment]
The logic looks perfect, remarks are only about style or commit isolation.

Great work!

You can keep as a single PR, I'll merge in fast-forward without merge-commit, each commit can be seen as a single task imo.

**Comment by aloiscochard** [comment]
Thanks for the great work @talw !

It's now merged into master.

**Comment by aloiscochard** [comment]
https://github.com/aloiscochard/codex/commit/6f5d6a33bfe57f9a2ca0915a7afa2360bc87133b

**Comment by talw** [comment]
With pleasure :+1:

**Pull request closed without merging**
