### PR TITLE
Swap out curl for wreq, and various Windows compatibility fixes

### PR DESCRIPTION
**Pull request by bmjames**
Using a portable HTTP client library makes it a bit easier to build codex out-of-the-box, especially on Windows.

The other fixes which were required to make it work correctly on Windows are:
  * Initialising networking with [`withSocketsDo`][1], an annoying but necessary bit of boilerplate
  * Double quotes around paths in shell commands, as the Windows shell doesn't like single quotes

Thanks for writing codex :smile:

~~:warning: NB: I've not yet tested these changes on a non-Windows environment!~~ Tested on Windows and OS X.

[1]: http://hackage.haskell.org/package/network-2.6.0.2/docs/Network-Socket-Internal.html#v:withSocketsDo

### CODE REVIEW

**Comment by aloiscochard** [comment]
I have rebased and pushed here:
https://github.com/aloiscochard/codex/tree/feature/windows-compat

I hope I did not messed up things!

I'll try it on Linux asap.

**Comment by bmjames** [comment]
The rebase looks good to me, except it introduces an unused import of `Control.Exception.tryJust` (which I think I introduced in one patch and then removed later).

**Comment by bmjames** [comment]
Pushed some changes since you did a rebase, so here's a new rebased branch.

**Comment by aloiscochard** [comment]
Finally merged (and tested on linux)!
https://github.com/aloiscochard/codex/commit/482c1d7d8a578cbd63d6486b53f2a67229a5c152

I'll release a `0.3` by the end of the day and annonce windows compat on the list.

Thanks a lot for your help bringing in windows compatibility!

**Pull request closed without merging**
